spring:
  datasource:
    url: jdbc:postgresql://39.105.121.125:5432/unibond
    username: unibond
    password: hFA1fzIvbistaZ3xKzStnQ6WXUA77LM
    hikari:
      max-lifetime: 300000
      keepalive-time: 120000
      validation-timeout: 5000
      connection-test-query: SELECT 1
  data:
    redis:
      host: 39.105.121.125
      port: 6379
      password: 7XEh3z07iWGeCZRDsstaHsoO5q4peQX
  mail:
    host: smtp.qq.com
    port: 465
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.ssl.enable: true

logging:
  level:
    com.unibond: DEBUG
    org.hibernate.SQL: DEBUG
